import Anthropic from '@anthropic-ai/sdk'
import type { ReportMode } from '../types/analysis'

// Claude Haiku is used only for structured listing-description extraction.
// Report verdict prose is deterministic and never generated by a language model.

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

export interface NarrativeInput {
  mode: ReportMode
  tier: 'free' | 'pro'
  address: string

  // Investment + Landlord (Report A / D)
  price?: number | null
  capRate?: number
  cashFlowMonthly?: number
  cashFlowAnnual?: number
  cashOnCash?: number
  dscr?: number
  dealScore?: number
  dealVerdict?: string
  rentMid?: number
  compCount?: number
  rentConfidence?: string
  breakEvenRent?: number
  condoFeeMonthly?: number | null
  condoFeeKnown?: boolean
  rentControlStatus?: string
  osfiResult?: string
  vacancyRate?: number
  rentTrend?: string
  riskFlagSummary?: string

  // Personal buyer (Report B)
  monthlyOwnershipCost?: number
  fmvLow?: number
  fmvHigh?: number
  pbCompCount?: number
  walkScore?: number | null
  transitScore?: number | null

  // Tenant (Report C)
  askingRent?: number
  rentLow?: number
  rentHigh?: number
  leverageLevel?: string
  leverageReason?: string
  lightScore?: number | null
}

function finite(value: number | null | undefined): value is number {
  return typeof value === 'number' && Number.isFinite(value)
}

function fmtCurrency(value: number): string {
  const rounded = Math.round(Math.abs(value)).toLocaleString('en-CA')
  return value < 0 ? `−$${rounded}` : `$${rounded}`
}

function fmtPct(value: number): string {
  return `${(value * 100).toFixed(2)}%`
}

function verdictLabel(verdict: string | undefined): string | null {
  if (!verdict) return null
  const labels: Record<string, string> = {
    strong_buy: 'strong deal',
    good_deal: 'good deal',
    caution: 'caution',
    marginal: 'marginal result',
    do_not_buy: 'do not buy',
    hard_pass: 'hard pass',
  }
  return labels[verdict] ?? null
}

function riskSentence(input: NarrativeInput, action: string): string {
  return input.riskFlagSummary
    ? `Review these structured risk flags ${action}: ${input.riskFlagSummary}.`
    : `No structured risk flags were identified from the available inputs; complete normal due diligence ${action}.`
}

function buildInvestorNarrative(input: NarrativeInput): string {
  const label = verdictLabel(input.dealVerdict)
  const opening = label
    ? `This property is a ${label} under the current assumptions.`
    : 'The investment verdict is unavailable because the calculation engine did not return a deal verdict.'

  const metrics: string[] = []
  if (finite(input.cashFlowMonthly))
    metrics.push(`monthly cash flow is ${fmtCurrency(input.cashFlowMonthly)}`)
  if (finite(input.capRate)) metrics.push(`cap rate is ${fmtPct(input.capRate)}`)
  if (finite(input.dscr)) metrics.push(`DSCR is ${input.dscr.toFixed(2)}×`)
  const metricSentence =
    metrics.length > 0
      ? `The calculated ${metrics.join(', ')}.`
      : 'Core investment metrics are unavailable, so no financial conclusion is stated.'

  const rentSentence =
    finite(input.rentMid) && (input.compCount ?? 0) > 0
      ? `The rent estimate is ${fmtCurrency(input.rentMid)}/month from ${input.compCount} comparable rentals with ${input.rentConfidence ?? 'unknown'} confidence.`
      : 'Comparable-rent evidence is unavailable, so any rent input should be treated as a low-confidence fallback.'

  const nextStep =
    input.dealVerdict === 'hard_pass' || input.dealVerdict === 'do_not_buy'
      ? 'Do not proceed on these assumptions. Recalculate only after verified rent, financing, fees, and inspection findings are available.'
      : 'Use the current result as a screening decision and verify rent, financing, fees, and inspection findings before making an offer.'

  return [
    opening,
    metricSentence,
    rentSentence,
    riskSentence(input, 'before proceeding'),
    nextStep,
  ].join(' ')
}

function buildPersonalNarrative(input: NarrativeInput): string {
  const priceSentence =
    finite(input.fmvLow) && finite(input.fmvHigh) && (input.pbCompCount ?? 0) > 0
      ? `The supplied fair-value range is ${fmtCurrency(input.fmvLow)} to ${fmtCurrency(input.fmvHigh)}, based on ${input.pbCompCount} comparable sales.`
      : 'Verified local comparable-sale evidence is unavailable, so this report does not claim the home is fairly priced.'
  const costSentence = finite(input.monthlyOwnershipCost)
    ? `The calculated ownership cost is ${fmtCurrency(input.monthlyOwnershipCost)}/month.`
    : 'A complete monthly ownership-cost figure was not supplied to the verdict service.'
  const mobility: string[] = []
  if (finite(input.walkScore)) mobility.push(`walk score ${Math.round(input.walkScore)}`)
  if (finite(input.transitScore)) mobility.push(`transit score ${Math.round(input.transitScore)}`)
  const mobilitySentence =
    mobility.length > 0
      ? `Available mobility data reports ${mobility.join(' and ')}.`
      : 'Walk and transit scores are unavailable for this address.'

  return [
    priceSentence,
    costSentence,
    mobilitySentence,
    riskSentence(input, 'before making an offer'),
    'Confirm financing, inspection findings, status documents, and closing costs before making an offer.',
  ].join(' ')
}

function buildTenantNarrative(input: NarrativeInput): string {
  const askingRent = finite(input.askingRent) ? input.askingRent : null
  const rentMid = finite(input.rentMid) ? input.rentMid : null
  const hasComps = rentMid !== null && (input.compCount ?? 0) > 0
  let position: string
  let action: string

  if (askingRent === null) {
    position =
      'The listing did not provide a usable asking rent, so this report cannot judge whether it is fairly priced.'
    action = 'Obtain the asking rent in writing before negotiating or signing.'
  } else if (!hasComps) {
    position = `The asking rent is ${fmtCurrency(askingRent)}/month, but no comparable rentals were available for a market benchmark.`
    action = 'Do not use an invented target; collect comparable rents before negotiating.'
  } else if (askingRent > rentMid) {
    position = `The asking rent is ${fmtCurrency(askingRent)}/month, above the ${fmtCurrency(rentMid)} market median from ${input.compCount} comparable rentals.`
    action = `Use the supplied market median of ${fmtCurrency(rentMid)}/month as a negotiation reference, not a guaranteed target.`
  } else {
    position = `The asking rent is ${fmtCurrency(askingRent)}/month, at or below the ${fmtCurrency(rentMid)} market median from ${input.compCount} comparable rentals.`
    action = 'The supplied median alone does not support a lower negotiation target.'
  }

  return [
    position,
    action,
    riskSentence(input, 'before signing'),
    'Confirm the lease terms, utilities, parking, and unit condition in writing before signing.',
  ].join(' ')
}

function buildLandlordNarrative(input: NarrativeInput): string {
  const label = verdictLabel(input.dealVerdict)
  const opening = label
    ? `The current landlord economics produce a ${label}.`
    : 'The landlord verdict is unavailable because the calculation engine did not return a deal verdict.'
  const position =
    finite(input.askingRent) && finite(input.rentMid) && (input.compCount ?? 0) > 0
      ? `The asking rent is ${fmtCurrency(input.askingRent)}/month against a ${fmtCurrency(input.rentMid)} median from ${input.compCount} comparable rentals.`
      : 'A supported asking-rent comparison is unavailable because the listing or comparable-rent inputs are incomplete.'
  const metrics: string[] = []
  if (finite(input.capRate)) metrics.push(`cap rate ${fmtPct(input.capRate)}`)
  if (finite(input.cashFlowMonthly))
    metrics.push(`monthly cash flow ${fmtCurrency(input.cashFlowMonthly)}`)
  const metricSentence =
    metrics.length > 0
      ? `The calculated economics show ${metrics.join(' and ')}.`
      : 'Calculated landlord economics are unavailable.'

  return [
    opening,
    position,
    metricSentence,
    riskSentence(input, 'before setting the rent'),
    'Verify the comparable units, lease terms, operating costs, and unit condition before publishing the rent.',
  ].join(' ')
}

/** Return deterministic verdict prose from validated structured inputs. */
export async function generateNarrative(input: NarrativeInput): Promise<string> {
  if (input.mode === 'investor') return buildInvestorNarrative(input)
  if (input.mode === 'personal') return buildPersonalNarrative(input)
  if (input.mode === 'tenant') return buildTenantNarrative(input)
  return buildLandlordNarrative(input)
}

/**
 * Extract structured flags from a listing description using Claude Haiku.
 * Returns a JSON object of flag keys and confidence scores.
 *
 * Never feed raw description text into deal score calculations.
 * All text must pass through this extraction pipeline first (spec Section 19).
 */
export async function extractListingFlags(description: string): Promise<Record<string, unknown>> {
  if (!description || !description.trim()) {
    return {}
  }

  const prompt = `Analyze this real estate listing description and extract structured flags.

Output ONLY valid JSON — no explanation, no preamble, no markdown fences.
For each flag, if there is no clear signal in the description, omit it
entirely. Default to omitting rather than guessing.

Each included flag must have this shape:
{ "confidence": <0-100>, "evidence": "<short quote from text, or null>" }

Flags to look for:
- glass_door_bedroom
- is_basement_unit
- parking_unclear
- unverified_bedroom
- special_assessment_risk
- tenanted
- str_history
- utilities_included
- utilities_extra
- needs_work
- pets_allowed
- no_pets

Listing description:
${description}`

  try {
    const response = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }],
    })

    const block = response.content[0]
    if (!block || block.type !== 'text') {
      return {}
    }

    let raw = block.text.trim()
    // Strip accidental markdown fences — the model occasionally adds them despite instructions
    raw = raw
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```$/i, '')
      .trim()

    let parsed: unknown
    try {
      parsed = JSON.parse(raw)
    } catch {
      console.error(
        `extractListingFlags: JSON parse failed, raw length=${raw.length}, preview="${raw.slice(0, 200)}"`
      )
      return {}
    }

    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      return {}
    }

    return parsed as Record<string, unknown>
  } catch (err) {
    console.error(
      `extractListingFlags: API error for description length=${description.length}:`,
      err
    )
    return {}
  }
}

export { client as anthropicClient }
